# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub
  - htmlzip

# Python configuration
python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: docs/requirements.txt

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      # Install the package in development mode
      - pip install -e .
